project_id = "zskktopasdqalyxurler"

[functions.chat]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.analytics-ingest]
verify_jwt = false

[functions.analytics-query]
verify_jwt = false